# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "factor2-affidavit"
client_id = "YOUR_CLIENT_ID"
application_url = "https://YOUR_APP_URL"
embedded = true

[access_scopes]
scopes = "read_customers,write_customers,read_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://YOUR_APP_URL/auth/callback",
  "https://YOUR_APP_URL/auth/shopify/callback",
  "https://YOUR_APP_URL/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "factor2inc.myshopify.com"
include_config_on_deploy = true

[app_proxy]
url = "https://YOUR_APP_URL"
subpath = "apps"
prefix = "affidavit"

